version: "3.9"

services:
  web:
    container_name: project-zero-cont
    image: cs50w/project-zero
    # tty: false               # false for `entrypoint` in Dockerfile
    # stdin_open: false        # false for `entrypoint` in Dockerfile
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: python main.py
    volumes:
    - .:/app
    ports:
    - ${PORT:-8000}:8000
